[project]
name = "reconciliations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.8",
    "pytest>=8.3.5",
    "xlsxwriter>=3.2.9",
]
